### PR TITLE
Changes tooltips that refer to "channels" as "components"

### PR DESCRIPTION
**Pull request by Shrinks99**
We refer to color channels as "channels" throughout the rest of the application (except in some _other_ places where they're referred to as "planes").  They should be referred to as channels in these nodes too for consistency and parity with many other software packages.

Also deletes a few rogue whitespaces :P

### CODE REVIEW

**Comment by devernay** [comment]
The OpenFX term is components, so it'll stay that way. Most people are clever enough to understand that components and channels are the same thing. Take for example the OpenFX specification: channel and component are used interchangeably https://readthedocs.org/projects/openfx/downloads/pdf/master/

"channels" is more British, "components" is more American, that's all.

**Comment by devernay** [comment]
there are more important things to fix, and think about it: OpenFX plugins are not only used in Natron

**Comment by Shrinks99** [comment]
Are Natron's openfx-misc plugins packaged or actually used with any other pieces of software?  I understand that they're generalized but are they actually used anywhere else?  In any case, the repo is owned by Natron's org and packaged within the program — labeling it as such isn't unreasonable at all.

It's not about if people are smart or not, it's about creating a cohesive experience where things make sense without actually having to think about them at all.  OFX can use whatever they like in their docs, we use "channels" in the viewer, "components" in some instances with nodes, and "planes" in others.  As I've said before this lack of consistency does not create a good user experience and I really think they should all be unified for the sake of clarity.  These things honestly confuse ME at times and I commit to the project :P

**Comment by devernay** [comment]
I don't think "plane" is used anywhere for "component" or "channel": a plane (aka layer) can have several components/channels.

OpenFX is an industry standard and uses "components" https://github.com/ofxa/openfx/blob/f6c60f92edc05578410d16f0eabe499b18e2507b/Documentation/sources/Reference/ofxClipPreferences.rst

**Comment by Shrinks99** [comment]
OpenFX is an industry standard, OpenEXR and OCIO are also industry standards.  That list above is 7 major software packages all of which explicitly use "channels" for user-facing labels and documentation.  I really think we'd only be doing a disservice to users for not following suit.  Alternatively, if we want to be special like OFX unify to components!  This will confuse people but hey, at least it will confuse people in a uniform manor.

I think you're correct about planes and layers, in the EXR read node both terms are used next to each-other as "Layer(s)" (outputChannels) and "All Planes" (processAllPlanes).
Screenshot 2021-03-26 213740

Will you at least agree that this level of inconsistency is a problem?

**Comment by devernay** [comment]
We could rename the tooltips to channels for colors, but "channel" is still an incorrect term for almost anything else than color:
- A position (x,y,z) has three components
- A normal (nx,ny,nz) has three components,
- Motion vectors (vx,vy) have two components, and are usually in two planes (forward, backward)

So "channel" cannot be used everywhere where "components" is used (whereas the reverse is true).

Note that the wikipedia page on [channels](https://en.wikipedia.org/wiki/Channel_(digital_image)) refers to color components, so I don't think using one for the other in some places will confuse users that much.

I think the "layer" term is a remnant from photoshop and after effects, and yes, these should be changed to "plane" everywhere, except where they make sense.

In a PSD or an XCF, where these are actual *ordered* layers, so you have the notion of a layer beign "on top" of another. This doesn't exist with planes.

**Comment by Shrinks99** [comment]
> We could rename the tooltips to channels for colors, but "channel" is still an incorrect term for almost anything else than color

Did I do this?  If so I have made an error, "channel" should absolutely only be used in reference to "colour channels".  I'm not arguing that referring to them as "components" isn't valid terminology, it's a commonly accepted term, what I am saying is that the way we refer to them in our interface that users look at needs to be consistent within itself and ideally match other very implementations.

As for layers VS planes, OpenEXR uses "layers" and their terms are consistent with other applications that implement the concept.  I would suggest we do the same here though I do acknowledge that this has potential conflicts with PSD systems as mentioned.

**Review by devernay — APPROVED** [review]

**Pull request merged**
