### PR TITLE
Fix denoisesharpen

### PR DESCRIPTION
**Pull request by devernay**
Combines https://github.com/NatronGitHub/openfx-misc/pull/62 and https://github.com/NatronGitHub/openfx-misc/pull/61

Should provide a better fix to https://github.com/NatronGitHub/Natron/issues/300 and https://github.com/NatronGitHub/openfx-misc/issues/60 than https://github.com/NatronGitHub/openfx-misc/pull/61

### CODE REVIEW

**Comment by devernay** [comment]
@yomgui1 can you please review the changes? It seems like it should really fix the bug this time. Thanks a lot for pointing out where the crash happened.

**Comment by yomgui1** [comment]
hmm no, it's incorrect somewhere.
I've tested and get following assertion in gdb:

Natron: ../DenoiseSharpen/DenoiseSharpen.cpp:2590: void {anonymous}::DenoiseSharpenPlugin::renderForBitDepth(const OFX::RenderArguments&) [with PIX = float; int nComponents = 3; int maxValue = 1]: Assertion `p.srcWindow.x1 <= x && x < p.srcWindow.x2 && p.srcWindow.y1 < y && y < p.srcWindow.y2' failed.

(gdb) p procWindow 
$4 = (const OfxRectI &) @0x7fffa103cf28: {x1 = 0, y1 = 0, x2 = 1156, y2 = 650}
(gdb) p p.srcWindow 
$5 = {x1 = 0, y1 = 0, x2 = 1156, y2 = 650}
(gdb) p x
$6 = 0
(gdb) p y
$7 = 0

**Comment by devernay** [comment]
fixed

**Comment by yomgui1** [comment]
raised the "never reach" assert with a 66% zoom

Natron: ../DenoiseSharpen/DenoiseSharpen.cpp:2588: void {anonymous}::DenoiseSharpenPlugin::renderForBitDepth(const OFX::RenderArguments&) [with PIX = float; int nComponents = 3; int maxValue = 1]: Assertion `false' failed.

(gdb) p srcPix 
$1 = (const float *) 0x0
(gdb) p procWindow 
$2 = (const OfxRectI &) @0x7fff06e64f28: {x1 = 0, y1 = 0, x2 = 1156, y2 = 650}
(gdb) p p.srcWindow 
$3 = {x1 = 0, y1 = 0, x2 = 1071, y2 = 559}

**Comment by devernay** [comment]
So the bug is probably still here
I would need:
- a trace of the previous call to getRegionsOfInterest (what was the ROI set on src)
- the bounds of src (p *src)

**Comment by devernay** [comment]
can you try it now? I found a bug and fixed it.
There is another bug in Natron, bug I won't fix it (getRegionsOfInterest should never be called if the effect does not support tiles), since it is only triggered by buggy plugins

**Comment by devernay** [comment]
@yomgui1  - ping

**Comment by yomgui1** [comment]
no crashes anymore. But the rendering is trashed after a certain level of zoom (around 80% in my case)

baddisplay

**Comment by yomgui1** [comment]
> @yomgui1 - ping

Was the night here ... ZZZzzzz :-)

**Comment by devernay** [comment]
It looks like the usual Natron cache bug. Does pressing "recycle" fix it?

**Comment by yomgui1** [comment]
yes it was a cache bug.

**Comment by danrhope** [comment]
Thanks very much for looking into this, Excited about the results!

**Pull request merged**
