### PR TITLE
MSVC Support

### PR DESCRIPTION
**Pull request by DrChat**
This PR adds support for MSVC (once again). Changes made:

 * Added a very simple CMakeLists.txt that I've only tested on Windows + MSVC.
 * A bunch of plugins included Windows.h when it wasn't needed - so I removed the include from most.
   * Windows.h defines min/max, which causes compiler errors when using std::min/max. I couldn't fix all of the cases where this error occurred so I just rage-defined NOMINMAX in the cmake file :)
 * MSVC does not play well with ifdef statements in assert statements, so those were ifdef'd out.
 * Define _USE_MATH_DEFINES for M_PI
 * Added GL/glext.h because MSVC does not have it installed.
 * It appears that I've updated the old project files by mistake - let me know if I should undo those changes (they didn't work in the first place anyways).

### CODE REVIEW

**Comment by devernay** [comment]
Thanks.
Can you please make another PR:
- without the vscode stuff
- windows.h should be capitalized consistently (let's say it's lowercase everywhere)
- why the changes to the vcprojs, since you use cmake anyway? I know the vcprojs are outdated, but let's keep these that way
- what's the issue with the asserts?
just make a clean branch, copy the necessary files to it, chack that only necessary changes are present, and make a new pr

**Comment by DrChat** [comment]
> what's the issue with the asserts?
VS is doing something weird when a preprocessor command is expanded inside of a macro (where that macro uses a stringize operator, I believe).

No need for a new PR - I'll screw with this one and try to remove the vscode commits and vcproj changes.

**Comment by DrChat** [comment]
I've rebased the PR and addressed a bunch of your concerns - still waiting for your input on the issue with asserts.

**Comment by devernay** [comment]
I think `#` preprocessor directives cannot be used inside macro parameters, so MSVC is right on this. I will merge PR and find a better solution for the asserts.

**Comment by DrChat** [comment]
Yeah - I wanted to get the shadertoy plugin working in Resolve for some cool (and free) FX!

For windows binaries, check out [Appveyor](https://www.appveyor.com). They build and host the binaries for you.

**Pull request merged**
